---
title: "Programming Languages for Data Science"
subtitle: "R & SQL"
author: 
  - .b[Jan Kirenz] .gray-2[&commat;jankirenz]
institute: ".small[.blue-medium[HdM Stuttgart]]"
date: '2021'
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: 
      - css/programming-xaringan.css
      - css/programming-xaringan-extra.css
      - css/talk-base.css
      - css/intro-prog.min.css
    seal: false
    nature:
      titleSlideClass: ["bottom", "left"]
      slideNumberFormat: "%current%"
      highlightStyle: atom-one-light
      highlightLines: true
      ratio: 16:9
      countIncrementalSlides: true
---

name: title
class: middle center hide-count
background-color: #FBFCFF;

```{r setup, echo=FALSE}
source("library.R")
source("setup.R")$value
```

<!-- Title Slide -->

<div class="city-360-rotate city-360-top"></div>
<div class="city-360-rotate city-360-bottom"></div>

Programming Languages 
Prof. Dr. Jan Kirenz


---
class: hide-count no-logo no-border bg-black

---
class: hide-count no-logo no-border bg-black

<div class="carina-nebula fullscreen-blur-fade-in"></div>


---
class: hide-count no-logo no-border bg-black carina-nebula-soft animated fadeIn

<div class="moons moons-1"><span class="moon-circle" style="background-color: #8FD3EE;"></span><span class="moons-text">Help you make a dashboard!</span></div>
<div class="moons moons-2"><span class="moon-circle" style="background-color: #8FD3EE;"></span><span class="moons-text">Fulfill your research data request!</span></div>
<div class="moons moons-3"><span class="moon-circle" style="background-color: #8FD3EE;"></span><span class="moons-text">Remember how the data got here!</span></div>
<div class="moons moons-4"><span class="moon-circle" style="background-color: #8FD3EE;"></span><span class="moons-text">Help you find that database!</span></div>
<div class="world world-it world-it1 rotate-zoom-in"></div>

???
The IT dept had many roles. 

---
class: hide-count no-logo no-border bg-black carina-nebula-soft

<div class="moons moons-1-static moons-text-reveal"><span class="moon-circle" style="background-color: #8FD3EE;"></span><span class="moons-text">Help you make a dashboard!</span></div>
<div class="moons moons-2-static"><span class="moon-circle" style="background-color: #8FD3EE;"></span><span class="moons-text">Fulfill your research data request!</span></div>
<div class="moons moons-4-static"><span class="moon-circle" style="background-color: #8FD3EE;"></span><span class="moons-text">Help you find that database!</span></div>
<div class="moons moons-3-static"><span class="moon-circle" style="background-color: #8FD3EE;"></span><span class="moons-text">Remember how the data got here!</span></div>
<div class="world world-it world-it1"></div>

???
Hospital operations needed dashboards for planning purposes

---
class: hide-count no-logo no-border bg-black carina-nebula-soft

<div class="moons moons-1-static moons-text-reveal"><span class="moon-circle" style="background-color: #8FD3EE;"></span><span class="moons-text">Help you make a dashboard!</span></div>
<div class="moons moons-2-static moons-text-reveal"><span class="moon-circle" style="background-color: #8FD3EE;"></span><span class="moons-text">Fulfill your research data request!</span></div>
<div class="moons moons-4-static"><span class="moon-circle" style="background-color: #8FD3EE;"></span><span class="moons-text">Help you find that database!</span></div>
<div class="moons moons-3-static"><span class="moon-circle" style="background-color: #8FD3EE;"></span><span class="moons-text">Remember how the data got here!</span></div>
<div class="world world-it world-it1"></div>

???
Researchers needed patient or biospecimen data for their IRB-approved protocols

---
class: hide-count no-logo no-border bg-black carina-nebula-soft

<div class="moons moons-1-static moons-text-reveal"><span class="moon-circle" style="background-color: #8FD3EE;"></span><span class="moons-text">Help you make a dashboard!</span></div>
<div class="moons moons-2-static moons-text-reveal"><span class="moon-circle" style="background-color: #8FD3EE;"></span><span class="moons-text">Fulfill your research data request!</span></div>
<div class="moons moons-3-static moons-text-reveal"><span class="moon-circle" style="background-color: #8FD3EE;"></span><span class="moons-text">Remember how the data got here!</span></div>
<div class="moons moons-4-static"><span class="moon-circle" style="background-color: #8FD3EE;"></span><span class="moons-text">Help you find that database!</span></div>
<div class="world world-it world-it1"></div>

???
Somebody needed to know about data lineage as well as coding or metadata standards; basically, how the data got here why it looks like it does

---
class: hide-count no-logo no-border bg-black carina-nebula-soft

<div class="moons moons-1-static moons-text-reveal"><span class="moon-circle" style="background-color: #8FD3EE;"></span><span class="moons-text">Help you make a dashboard!</span></div>
<div class="moons moons-2-static moons-text-reveal"><span class="moon-circle" style="background-color: #8FD3EE;"></span><span class="moons-text">Fulfill your research data request!</span></div>
<div class="moons moons-4-static moons-text-reveal"><span class="moon-circle" style="background-color: #8FD3EE;"></span><span class="moons-text">Help you find that database!</span></div>
<div class="moons moons-3-static moons-text-reveal"><span class="moon-circle" style="background-color: #8FD3EE;"></span><span class="moons-text">Remember how the data got here!</span></div>
<div class="world world-it world-it1"></div>

???
Organizing databases into a warehouse and granting access was important. We had someone for that!

But eventually, some of these teams were operating at a scale which would be better situated as independent of the IT gravity field

---
name: world-bi
class: hide-count no-logo no-border bg-black carina-nebula-soft fullscreen

<div class="absolute top-0 left-0 right-0 bottom-0 zoomToStepOne">
<div class="moons moons-1-static moons-text-reveal animated fadeOut"><span class="moon-circle" style="background-color: #8FD3EE;"></span><span class="moons-text">Help you make a dashboard!</span></div>
<div class="moons moons-2-static moons-text-reveal"><span class="moon-circle" style="background-color: #8FD3EE;"></span><span class="moons-text">Fulfill your research data request!</span></div>
<div class="moons moons-3-static moons-text-reveal"><span class="moon-circle" style="background-color: #8FD3EE;"></span><span class="moons-text">Remember how the data got here!</span></div>
<div class="moons moons-4-static moons-text-reveal"><span class="moon-circle" style="background-color: #8FD3EE;"></span><span class="moons-text">Help you find that database!</span></div>
<div class="world world-it world-it1"></div>
</div>

<div class="world world-bi world-bi-entrance" style="width: 160px; height: 160px; top: 10%; left: 60%;"></div>
<div class="world-label world-label-bi white">Business<br>Intelligence</div>

???
One of these, was business intelligence. That person who was making dashboards for operational, i.e. non-research stakeholders, is now part of a larger team that creates such products at scale

---
name: world-cdsc
class: hide-count no-logo no-border bg-black carina-nebula-soft fullscreen

<div class="absolute top-0 left-0 right-0 bottom-0 zoomToStepTwo">
<div class="moons moons-2-static moons-text-reveal animated fadeOut"><span class="moon-circle" style="background-color: #8FD3EE;"></span><span class="moons-text">Fulfill your research data request!</span></div>
<div class="moons moons-4-static moons-text-reveal"><span class="moon-circle" style="background-color: #8FD3EE;"></span><span class="moons-text">Help you find that database!</span></div>
<div class="moons moons-3-static moons-text-reveal"><span class="moon-circle" style="background-color: #8FD3EE;"></span><span class="moons-text">Remember how the data got here!</span></div>
<div class="world world-it world-it1"></div>
</div>

<div class="world world-bi"></div>
<div class="world-label world-label-bi white">Business<br>Intelligence</div>

<div class="world world-cdsc"></div>
<div class="world-label world-label-cdsc white">Collaborative<br>Data<br>Services</div>

???
Next, our research-focused stakeholders had many of the same needs as the operational end-users, such as reporting/dashboarding and, importantly data provisioning. The twist in the research space is that such activities must be conducted in accordance with IRB and ethical approval, and study design feasibility as it relates to data availability and structure requires specialized training. Hence, the CDS team was formed. This is one of the groups that Garrick and I are representing today.

---
name: world-dqs
class: hide-count no-logo no-border bg-black carina-nebula-soft fullscreen

<div class="absolute top-0 left-0 right-0 bottom-0 zoomToStepThree">
<div class="moons moons-3-static moons-text-reveal animated fadeOut"><span class="moon-circle" style="background-color: #8FD3EE;"></span><span class="moons-text">Remember how the data got here!</span></div>
<div class="moons moons-4-static moons-text-reveal"><span class="moon-circle" style="background-color: #8FD3EE;"></span><span class="moons-text">Help you find that database!</span></div>
<div class="world world-it world-it1"></div>
</div>

<div class="world world-bi"></div>
<div class="world-label world-label-bi white">Business<br>Intelligence</div>

<div class="world world-cdsc"></div>
<div class="world-label world-label-cdsc white">Collaborative<br>Data<br>Services</div>

<div class="world world-dqs"></div>
<div class="world-label world-label-dqs white">Data<br>Quality</div>

???
But CDS can't operate at scale in a vacuum either. A critical and complementary team, Data Quality and Standards, formed from IT's "data historian." They ensure that data dictionaries are robust and data lineage is understood by the BI and CDS teams for appropriate downstream data usage. 

---
name: data-engineering
class: hide-count no-logo no-border bg-black carina-nebula-soft fullscreen

<div class="absolute top-0 left-0 right-0 bottom-0 zoomStepThree">
<div class="moons moons-4-static moons-text-reveal"><span class="moon-circle" style="background-color: #8FD3EE;"></span><span class="moons-text">Help you find that database!</span></div>
<div class="world world-it world-it2"></div>
<div class="world world-it world-it1"></div>
</div>

<div class="world world-bi"></div>
<div class="world-label world-label-bi white">Business<br>Intelligence</div>

<div class="world world-cdsc"></div>
<div class="world-label world-label-cdsc white">Collaborative<br>Data<br>Services</div>

<div class="world world-dqs"></div>
<div class="world-label world-label-dqs white">Data<br>Quality</div>

???
As institutional data assets grew, warehousing and access rules became necessarily complex. Data engineering formed a new continent within IT to meet the challenge.

---
name: rocket
class: hide-count no-logo no-border bg-black carina-nebula-soft fullscreen

<div class="absolute top-0 left-0 right-0 bottom-0 zoomStepThree">
<div class="world world-it world-it2"></div>
</div>

<div class="world world-bi"></div>
<div class="world-label world-label-bi white">Business<br>Intelligence</div>

<div class="world world-cdsc"></div>
<div class="world-label world-label-cdsc white">Collaborative<br>Data<br>Services</div>

<div class="world world-dqs"></div>
<div class="world-label world-label-dqs white">Data<br>Quality</div>

<div class="rocket rocket-entrance"></div>

???
Now, with so many teams completing data-related operations at a rapid pace, we needed a shuttlecraft to coordinate technology strategy, inform general data governance, and mine valuable software ore from the astRoid belt

---
name: app-dev
class: hide-count no-logo no-border bg-black carina-nebula-soft fullscreen animated fadeIn

<div class="absolute top-0 left-0 right-0 bottom-0 zoomStepThree">
<div class="world world-it world-it2"></div>
<div class="world world-it world-it3"></div>
</div>

<div class="world world-bi"></div>
<div class="world-label world-label-bi white">Business<br>Intelligence</div>

<div class="world world-cdsc"></div>
<div class="world-label world-label-cdsc white">Collaborative<br>Data<br>Services</div>

<div class="world world-dqs"></div>
<div class="world-label world-label-dqs white">Data<br>Quality</div>

<div class="rocket"></div>

<div class="world-label-it">IT</div>

???
When those tools are ready for placement and maintenance in the institutionally supported production environment, the new Applications Development land mass within IT can help out. For example, they would maintain software such as RStudio Server or GitHub Enterprise.

---
name: cdo
class: hide-count no-logo no-border bg-black carina-nebula-soft fullscreen animated fadeIn

<div class="absolute top-0 left-0 right-0 bottom-0 zoomStepThree">
<div class="world world-it world-it3"></div>
</div>

<div class="world world-bi"></div>
<div class="world-label world-label-bi white">Business<br>Intelligence</div>

<div class="world world-cdsc"></div>
<div class="world-label world-label-cdsc white">Collaborative<br>Data<br>Services</div>

<div class="world world-dqs"></div>
<div class="world-label world-label-dqs white">Data<br>Quality</div>

<div class="rocket"></div>

<div class="world-label-it">IT</div>

<div class="space-person vibrate-1"></div>

???
This whole story, admittedly with some shortcuts for clarity, mirrors the rise of the Chief Data Officer role across the healthcare industry. Indeed, all of these groups tend to roll up or be horizontally aligned in some way with the CDO's vertical.

---
class: left middle blueprint2

.f4[
Scaling .b.blue[provisioning]<br>
by scaling .b.em.red[people]
]

.absolute.bottom-1.right-1[

]

???
Taken together, this is our first hint that scaling data provisioning isn't just about scaling data: it's about scaling the people who are doing the provisioning. In part 2, Garrick is going to tell you more about the "how"

---
class: left middle blueprint2

.f4[
[...continued in part 2 &rarr;](part-two.html)
]

